### PR TITLE
Promisify redis

### PR DESCRIPTION
**Pull request by ecwyne**
Per redis docs https://github.com/NodeRedis/node_redis#promises

This allows promise-returning redis methods. Makes things easier to work with when using Redis in Hydra

### CODE REVIEW

**Review by emadum — APPROVED** [review]
Good call, I usually do this in my microservices but it's probably smarter to do it once here. @cjus, any thoughts?

**Comment by ecwyne** [comment]
@cjus Wanted to make sure this didn't fall through the cracks. I actually just found out I've got a bug in `hydra-plugin-rpc` that expected the redis instance to be promisified already.

**Comment by emadum** [comment]
I'll merge it in now


Sent from my iPhone

On Apr 20, 2017, at 1:20 PM, Eric Wyne <notifications@github.com<mailto:notifications@github.com>> wrote:


@cjus<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcjus&data=01%7C01%7Ceric%40flywheelsports.com%7Ceb4448115e6b4e0c13a008d488117c9a%7Ce110a28e5f4f4e558488575a2ed46dbc%7C0&sdata=0GUfP%2Bet%2BoFkjoCPIH9qiw1q7MVoS1EVgiPadUViekc%3D&reserved=0> Wanted to make sure this didn't fall through the cracks. I actually just found out I've got a bug in hydra-plugin-rpc that expected the redis instance to be promisified already.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fflywheelsports%2Ffwsp-redis-connection%2Fpull%2F1%23issuecomment-295822945&data=01%7C01%7Ceric%40flywheelsports.com%7Ceb4448115e6b4e0c13a008d488117c9a%7Ce110a28e5f4f4e558488575a2ed46dbc%7C0&sdata=cCflpDSgTfwTh8nKb5UJeSjTKUljHvAKP6Wk0rPMTJ8%3D&reserved=0>, or mute the thread<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAASVeb5sIJUg1e-v8oC0h7Aef37T0Z3Tks5rx5PCgaJpZM4M_vrX&data=01%7C01%7Ceric%40flywheelsports.com%7Ceb4448115e6b4e0c13a008d488117c9a%7Ce110a28e5f4f4e558488575a2ed46dbc%7C0&sdata=aGIer59bAQqVfanB9dJZH%2BX%2FDGXntfogrv%2FOjOslFxM%3D&reserved=0>.

This message contains confidential information and is intended only for the individual named. If you are not the named addressee you should not disseminate, distribute or copy this e-mail. Please notify the sender immediately by e-mail if you have received this e-mail by mistake and delete this e-mail from your system. E-mail transmission cannot be guaranteed to be secure or error-free as information could be intercepted, corrupted, lost, destroyed, arrive late or incomplete, or contain viruses. The sender therefore does not accept liability for any errors or omissions in the contents of this message, which arise as a result of e-mail transmission. If verification is required please request a hard-copy version.

**Comment by ecwyne** [comment]
@emadum Thanks for merging! Can we publish 0.0.3 and update hydra?

**Comment by emadum** [comment]
I bumped the version and published. @cjus should I update hydra or do you want to?

**Comment by ecwyne** [comment]
Thanks!

**Pull request merged**
